"""Fuzzing Harness Generator: Generate fuzzers from vulnerability patterns.

Takes crash analysis results or CVE patterns and generates:
  - Python-native fuzzers (no external deps)
  - AFL-compatible harness (C)
  - libFuzzer harness (C)
  - Protocol-specific fuzzers (HTTP, DNS, TLS, etc.)

Each generated harness:
  1. Creates inputs targeting the specific vulnerability class
  2. Monitors for crashes (SIGSEGV, SIGABRT, etc.)
  3. Minimizes crashing inputs
  4. Reports findings with exploit primitive classification

Part of FORGE Phase K: Fuzzing Harness Generator.
"""
# Dependencies: none
# Depended by: hunt_loop

import json
import os
import struct
import textwrap
from typing import Any, Dict, List, Optional, Tuple


class FuzzGenerator:
    """Generate fuzzing harnesses from vulnerability patterns."""

    def __init__(self):
        self.generators = {
            'python_mutator': self._gen_python_mutator,
            'python_protocol': self._gen_python_protocol,
            'afl_harness': self._gen_afl_harness,
            'libfuzzer_harness': self._gen_libfuzzer_harness,
            'macho_fuzzer': self._gen_macho_fuzzer,
            'format_fuzzer': self._gen_format_fuzzer,
        }

    def generate(self, vuln_type: str, target_info: Dict,
                 harness_type: str = 'python_mutator') -> str:
        """Generate a fuzzing harness.

        Args:
            vuln_type: Vulnerability type (buffer_overflow, uaf, integer_overflow,
                       null_deref, format_string, command_injection)
            target_info: Dict with target details:
                - binary: path to target binary
                - function: target function name
                - input_type: 'file', 'stdin', 'network', 'arg'
                - protocol: optional protocol (http, dns, tls, etc.)
                - cve_id: optional CVE reference
                - cwe: optional CWE ID
                - crash_log: optional crash analysis dict
            harness_type: Type of harness to generate

        Returns:
            Generated harness code as string
        """
        generator = self.generators.get(harness_type)
        if not generator:
            raise ValueError(f"Unknown harness type: {harness_type}. "
                             f"Available: {', '.join(self.generators.keys())}")

        return generator(vuln_type, target_info)

    def generate_from_crash(self, crash_analysis: Dict) -> str:
        """Generate fuzzer from crash analysis result.

        Takes output from CrashAnalyzer.analyze_file() and generates
        a targeted fuzzer.
        """
        primitive = crash_analysis.get('primitive', {})
        ptype = primitive.get('type', 'dos')

        # Map primitive to vulnerability type
        vuln_map = {
            'dos': 'null_deref',
            'info_leak': 'buffer_overflow',
            'write': 'buffer_overflow',
            'execute': 'uaf',
        }
        vuln_type = vuln_map.get(ptype, 'buffer_overflow')

        target_info = {
            'binary': crash_analysis.get('app', 'target'),
            'function': crash_analysis.get('crashing_function', 'unknown'),
            'input_type': 'file',
            'faulting_address': crash_analysis.get('faulting_address', '0x0'),
            'signal': crash_analysis.get('signal', 'SIGSEGV'),
            'crash_analysis': crash_analysis,
        }

        return self.generate(vuln_type, target_info, 'python_mutator')

    def generate_from_cve(self, cve) -> str:
        """Generate fuzzer from CVE entry.

        Takes CVEEntry from cve_fetcher and generates a targeted fuzzer.
        """
        target_info = {
            'binary': 'target',
            'function': 'parse_input',
            'input_type': 'file',
            'cve_id': cve.cve_id,
            'cwe': cve.cwes[0] if cve.cwes else '',
            'description': cve.description[:200],
            'attack_vector': cve.attack_vector,
        }

        vuln_map = {
            'write': 'buffer_overflow',
            'execute': 'uaf',
            'info_leak': 'buffer_overflow',
            'dos': 'null_deref',
        }
        vuln_type = vuln_map.get(cve.exploit_primitive, 'buffer_overflow')

        return self.generate(vuln_type, target_info, 'python_mutator')

    # ─── Generator Implementations ──────────────────────────────

    def _gen_python_mutator(self, vuln_type: str, info: Dict) -> str:
        """Generate Python mutation-based fuzzer."""
        mutation_strategies = self._get_mutation_strategies(vuln_type)

        return textwrap.dedent(f'''\
            #!/usr/bin/env python3
            """FORGE Mutation Fuzzer — {vuln_type}

            Target: {info.get('binary', 'target')}
            Function: {info.get('function', 'unknown')}
            CVE: {info.get('cve_id', 'N/A')}
            CWE: {info.get('cwe', 'N/A')}

            Generated by FORGE — deterministic, zero AI.
            """
            import hashlib
            import os
            import random
            import signal
            import struct
            import subprocess
            import sys
            import tempfile
            import time


            # ─── Configuration ────────────────────────────────────────
            TARGET_BINARY = "{info.get('binary', './target')}"
            INPUT_TYPE = "{info.get('input_type', 'file')}"
            MAX_ITERATIONS = 100000
            MAX_INPUT_SIZE = 65536
            TIMEOUT = 5
            CRASH_DIR = "crashes"
            CORPUS_DIR = "corpus"

            # ─── Mutation Strategies ──────────────────────────────────

            {mutation_strategies}

            # ─── Fuzzer Core ──────────────────────────────────────────

            class Fuzzer:
                def __init__(self):
                    self.iterations = 0
                    self.crashes = 0
                    self.unique_crashes = set()
                    self.corpus = []
                    self.start_time = time.time()
                    os.makedirs(CRASH_DIR, exist_ok=True)
                    os.makedirs(CORPUS_DIR, exist_ok=True)

                def seed_corpus(self):
                    """Initialize corpus with seed inputs."""
                    # Seed based on vulnerability type
                    seeds = generate_seeds()
                    for seed in seeds:
                        self.corpus.append(seed)
                    if not self.corpus:
                        self.corpus.append(os.urandom(64))

                def mutate(self, data):
                    """Apply random mutation strategy."""
                    strategies = [
                        bit_flip, byte_flip, insert_bytes, delete_bytes,
                        replace_with_interesting, duplicate_block,
                        crossover if len(self.corpus) > 1 else bit_flip,
                    ]
                    strategy = random.choice(strategies)
                    if strategy == crossover:
                        other = random.choice(self.corpus)
                        return strategy(data, other)
                    return strategy(data)

                def run_target(self, input_data):
                    """Run target with input and check for crash."""
                    with tempfile.NamedTemporaryFile(delete=False, dir='/tmp') as f:
                        f.write(input_data)
                        tmppath = f.name

                    try:
                        if INPUT_TYPE == 'file':
                            result = subprocess.run(
                                [TARGET_BINARY, tmppath],
                                capture_output=True, timeout=TIMEOUT)
                        elif INPUT_TYPE == 'stdin':
                            result = subprocess.run(
                                [TARGET_BINARY],
                                input=input_data,
                                capture_output=True, timeout=TIMEOUT)
                        else:
                            result = subprocess.run(
                                [TARGET_BINARY, tmppath],
                                capture_output=True, timeout=TIMEOUT)

                        # Check for crash signals
                        if result.returncode < 0:
                            sig = -result.returncode
                            if sig in (signal.SIGSEGV, signal.SIGBUS, signal.SIGABRT,
                                       signal.SIGFPE, signal.SIGILL):
                                return True, sig, result.stderr
                        return False, 0, b''

                    except subprocess.TimeoutExpired:
                        return False, 0, b'timeout'
                    except FileNotFoundError:
                        return False, 0, b'binary not found'
                    finally:
                        os.unlink(tmppath)

                def save_crash(self, input_data, sig, stderr):
                    """Save crashing input."""
                    crash_hash = hashlib.sha256(input_data).hexdigest()[:16]
                    if crash_hash in self.unique_crashes:
                        return False

                    self.unique_crashes.add(crash_hash)
                    self.crashes += 1

                    sig_name = {{
                        signal.SIGSEGV: 'SIGSEGV',
                        signal.SIGBUS: 'SIGBUS',
                        signal.SIGABRT: 'SIGABRT',
                        signal.SIGFPE: 'SIGFPE',
                        signal.SIGILL: 'SIGILL',
                    }}.get(sig, f'SIG{{sig}}')

                    crash_file = os.path.join(CRASH_DIR,
                        f'crash_{{sig_name}}_{{crash_hash}}.bin')
                    with open(crash_file, 'wb') as f:
                        f.write(input_data)

                    info_file = crash_file + '.info'
                    with open(info_file, 'w') as f:
                        f.write(f'Signal: {{sig_name}}\\n')
                        f.write(f'Size: {{len(input_data)}} bytes\\n')
                        f.write(f'SHA256: {{hashlib.sha256(input_data).hexdigest()}}\\n')
                        f.write(f'Iteration: {{self.iterations}}\\n')
                        f.write(f'Stderr: {{stderr[:500]}}\\n')

                    return True

                def fuzz(self, max_iterations=MAX_ITERATIONS):
                    """Main fuzzing loop."""
                    self.seed_corpus()
                    print(f"FORGE Fuzzer — {{len(self.corpus)}} seeds, target: {{TARGET_BINARY}}")
                    print(f"Crash dir: {{CRASH_DIR}}/")

                    for i in range(max_iterations):
                        self.iterations = i + 1

                        # Pick and mutate
                        base = random.choice(self.corpus)
                        mutated = self.mutate(base)

                        # Truncate if too large
                        if len(mutated) > MAX_INPUT_SIZE:
                            mutated = mutated[:MAX_INPUT_SIZE]

                        # Run target
                        crashed, sig, stderr = self.run_target(mutated)

                        if crashed:
                            is_new = self.save_crash(mutated, sig, stderr)
                            if is_new:
                                print(f"  [{{i+1}}] NEW CRASH! Signal={{sig}}, "
                                      f"size={{len(mutated)}}, "
                                      f"total={{self.crashes}}")
                                # Add to corpus for further mutation
                                self.corpus.append(mutated)

                        # Progress
                        if (i + 1) % 1000 == 0:
                            elapsed = time.time() - self.start_time
                            rate = (i + 1) / elapsed if elapsed > 0 else 0
                            print(f"  [{{i+1}}] {{rate:.0f}} exec/s, "
                                  f"{{self.crashes}} crashes, "
                                  f"{{len(self.unique_crashes)}} unique, "
                                  f"corpus={{len(self.corpus)}}")

                    elapsed = time.time() - self.start_time
                    print(f"\\nDone: {{self.iterations}} iterations in {{elapsed:.1f}}s")
                    print(f"Crashes: {{self.crashes}} total, "
                          f"{{len(self.unique_crashes)}} unique")


            if __name__ == "__main__":
                fuzzer = Fuzzer()
                fuzzer.fuzz()
        ''')

    def _gen_python_protocol(self, vuln_type: str, info: Dict) -> str:
        """Generate protocol-specific fuzzer."""
        protocol = info.get('protocol', 'http')

        return textwrap.dedent(f'''\
            #!/usr/bin/env python3
            """FORGE Protocol Fuzzer — {protocol.upper()} / {vuln_type}

            Target: {info.get('binary', 'target')}
            Protocol: {protocol}
            CVE: {info.get('cve_id', 'N/A')}

            Generated by FORGE — deterministic, zero AI.
            """
            import socket
            import struct
            import random
            import os
            import sys
            import time


            TARGET_HOST = "{info.get('target_host', '127.0.0.1')}"
            TARGET_PORT = {info.get('target_port', 80)}
            MAX_ITERATIONS = 10000
            TIMEOUT = 3


            def generate_fuzzed_{protocol}_request():
                """Generate a fuzzed {protocol} request."""
                methods = ['GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'OPTIONS',
                           'A' * 1000, '\\x00' * 10, 'GET' * 100]
                paths = ['/', '/index.html', '/' + 'A' * 4096,
                         '/../' * 100 + 'etc/passwd',
                         '/?' + 'x=' + 'A' * 8192]
                headers = [
                    'Host: ' + 'A' * random.randint(1, 8192),
                    'Content-Length: ' + str(random.choice([0, -1, 0x7FFFFFFF, 0xFFFFFFFF])),
                    'Transfer-Encoding: chunked\\r\\n0\\r\\n\\r\\n' + 'A' * 1024,
                ]

                method = random.choice(methods)
                path = random.choice(paths)
                header = random.choice(headers)

                return f'{{method}} {{path}} HTTP/1.1\\r\\n{{header}}\\r\\n\\r\\n'.encode()


            def fuzz():
                """Main protocol fuzzing loop."""
                crashes = 0
                errors = 0

                for i in range(MAX_ITERATIONS):
                    payload = generate_fuzzed_{protocol}_request()

                    try:
                        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
                        sock.settimeout(TIMEOUT)
                        sock.connect((TARGET_HOST, TARGET_PORT))
                        sock.sendall(payload)

                        try:
                            response = sock.recv(4096)
                            if not response:
                                errors += 1
                        except socket.timeout:
                            pass

                        sock.close()

                    except ConnectionRefusedError:
                        crashes += 1
                        crash_file = f'crashes/proto_crash_{{i}}.bin'
                        os.makedirs('crashes', exist_ok=True)
                        with open(crash_file, 'wb') as f:
                            f.write(payload)
                        print(f'[{{i}}] TARGET DOWN after {{len(payload)}} byte payload')
                        time.sleep(2)  # Wait for restart
                    except Exception:
                        errors += 1

                    if (i + 1) % 500 == 0:
                        print(f'[{{i+1}}] {{crashes}} crashes, {{errors}} errors')

                print(f'Done: {{crashes}} crashes in {{MAX_ITERATIONS}} iterations')


            if __name__ == "__main__":
                fuzz()
        ''')

    def _gen_afl_harness(self, vuln_type: str, info: Dict) -> str:
        """Generate AFL-compatible C harness."""
        return textwrap.dedent(f'''\
            /* FORGE AFL Harness — {vuln_type}
             *
             * Target: {info.get('binary', 'target')}
             * Function: {info.get('function', 'parse_input')}
             * CVE: {info.get('cve_id', 'N/A')}
             *
             * Compile: afl-gcc -o harness harness.c -fsanitize=address
             * Run: afl-fuzz -i corpus/ -o findings/ -- ./harness @@
             *
             * Generated by FORGE — deterministic, zero AI.
             */

            #include <stdio.h>
            #include <stdlib.h>
            #include <string.h>
            #include <unistd.h>

            #define MAX_INPUT_SIZE 65536

            /* Forward declaration — link against target library */
            extern int {info.get('function', 'parse_input')}(const unsigned char *data, size_t len);

            int main(int argc, char **argv) {{
                FILE *fp;
                unsigned char buf[MAX_INPUT_SIZE];
                size_t len;

                if (argc < 2) {{
                    /* Read from stdin for AFL persistent mode */
                    len = fread(buf, 1, MAX_INPUT_SIZE, stdin);
                }} else {{
                    fp = fopen(argv[1], "rb");
                    if (!fp) return 1;
                    len = fread(buf, 1, MAX_INPUT_SIZE, fp);
                    fclose(fp);
                }}

                if (len == 0) return 0;

                /* Call target function */
                {info.get('function', 'parse_input')}(buf, len);

                return 0;
            }}
        ''')

    def _gen_libfuzzer_harness(self, vuln_type: str, info: Dict) -> str:
        """Generate libFuzzer C harness."""
        return textwrap.dedent(f'''\
            /* FORGE libFuzzer Harness — {vuln_type}
             *
             * Target: {info.get('binary', 'target')}
             * Function: {info.get('function', 'parse_input')}
             * CVE: {info.get('cve_id', 'N/A')}
             *
             * Compile: clang -g -fsanitize=fuzzer,address -o harness harness.c target.c
             * Run: ./harness corpus/
             *
             * Generated by FORGE — deterministic, zero AI.
             */

            #include <stdint.h>
            #include <stddef.h>
            #include <string.h>

            /* Forward declaration — link against target library */
            extern int {info.get('function', 'parse_input')}(const unsigned char *data, size_t len);

            int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size) {{
                if (size == 0 || size > 65536)
                    return 0;

                /* Call target function */
                {info.get('function', 'parse_input')}(data, size);

                return 0;
            }}
        ''')

    def _gen_macho_fuzzer(self, vuln_type: str, info: Dict) -> str:
        """Generate Mach-O binary fuzzer targeting code signature parsing."""
        return textwrap.dedent(f'''\
            #!/usr/bin/env python3
            """FORGE Mach-O Fuzzer — Code Signature Parsing

            Generates malformed Mach-O binaries to test code signature parsers.
            Targets: syspolicyd, codesign, spctl, Security.framework

            CVE: {info.get('cve_id', 'N/A')}
            Generated by FORGE — deterministic, zero AI.
            """
            import hashlib
            import os
            import random
            import struct
            import subprocess
            import sys
            import tempfile
            import time


            # Mach-O constants
            MH_MAGIC_64 = 0xFEEDFACF
            LC_SEGMENT_64 = 0x19
            LC_CODE_SIGNATURE = 0x1D
            CSMAGIC_EMBEDDED_SIGNATURE = 0xFADE0CC0
            CSMAGIC_CODEDIRECTORY = 0xFADE0C02

            CRASH_DIR = "crashes"


            def build_macho(text_size=4096):
                """Build a minimal valid Mach-O binary."""
                # Header
                header = struct.pack('<IIIIIIII',
                    MH_MAGIC_64,     # magic
                    0x0100000C,      # cpu: arm64
                    0x00000000,      # cpusub
                    2,               # filetype: MH_EXECUTE
                    2,               # ncmds
                    0,               # sizeofcmds (filled later)
                    0x00200085,      # flags: PIE|TWOLEVEL|DYLDLINK|NOUNDEFS
                    0)               # reserved

                # __TEXT segment
                seg = struct.pack('<II', LC_SEGMENT_64, 72)
                seg += b'__TEXT\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00'
                seg += struct.pack('<QQQQ', 0x100000000, text_size, 0, text_size)
                seg += struct.pack('<IIII', 5, 5, 0, 0)

                # LC_CODE_SIGNATURE (will point past __TEXT)
                cs_off = len(header) + len(seg) + 16 + text_size
                cs_lc = struct.pack('<IIII', LC_CODE_SIGNATURE, 16, cs_off, 0)

                # Fix sizeofcmds
                sizeofcmds = len(seg) + len(cs_lc)
                header = header[:20] + struct.pack('<I', sizeofcmds) + header[24:]

                # Pad __TEXT
                body = header + seg + cs_lc
                body += b'\\xc0\\x03\\x5f\\xd6' * (text_size // 4)  # ARM64 RET

                return bytearray(body), cs_off


            def build_codesig_fuzzed():
                """Build a Mach-O with fuzzed code signature."""
                macho, cs_off = build_macho()

                # Mutation strategy
                strategy = random.choice([
                    'huge_ncodeslots',
                    'huge_blob_count',
                    'negative_offset',
                    'zero_length',
                    'bad_magic',
                    'huge_hash_size',
                    'overlapping_blobs',
                    'truncated_cd',
                ])

                cs_data = bytearray()

                if strategy == 'huge_ncodeslots':
                    # SuperBlob
                    cs_data += struct.pack('>III', CSMAGIC_EMBEDDED_SIGNATURE, 0, 1)
                    cs_data += struct.pack('>II', 0, 20)  # blob index
                    # CodeDirectory with overflow nCodeSlots
                    cd_start = len(cs_data)
                    cs_data += struct.pack('>II', CSMAGIC_CODEDIRECTORY, 0)
                    cs_data += struct.pack('>I', 0x20400)  # version
                    cs_data += struct.pack('>I', 0)  # flags
                    cs_data += struct.pack('>I', 80)  # hashOffset
                    cs_data += struct.pack('>I', 52)  # identOffset
                    cs_data += struct.pack('>I', 0)  # nSpecialSlots
                    cs_data += struct.pack('>I', 0x80000001)  # nCodeSlots = OVERFLOW
                    cs_data += struct.pack('>I', 4096)  # codeLimit
                    cs_data += struct.pack('>B', 32)  # hashSize
                    cs_data += struct.pack('>B', 2)  # hashType SHA256
                    cs_data += struct.pack('>BB', 0, 12)  # spare, pageSize
                    cs_data += struct.pack('>I', 0)  # spare2
                    cs_data += b'test.fuzz\\x00'
                    cs_data += b'\\x00' * (80 - (len(cs_data) - cd_start - 8))
                    cs_data += os.urandom(32)  # one hash slot
                    # Fix lengths
                    cd_len = len(cs_data) - cd_start
                    struct.pack_into('>I', cs_data, cd_start + 4, cd_len)
                    struct.pack_into('>I', cs_data, 4, len(cs_data))

                elif strategy == 'huge_blob_count':
                    cs_data += struct.pack('>III', CSMAGIC_EMBEDDED_SIGNATURE, 100, 0xFFFFFFFF)
                    cs_data += os.urandom(64)

                elif strategy == 'negative_offset':
                    cs_data += struct.pack('>III', CSMAGIC_EMBEDDED_SIGNATURE, 40, 1)
                    cs_data += struct.pack('>II', 0, 0xFFFFFFF0)  # negative offset
                    cs_data += os.urandom(16)

                elif strategy == 'zero_length':
                    cs_data += struct.pack('>III', CSMAGIC_EMBEDDED_SIGNATURE, 0, 1)
                    cs_data += struct.pack('>II', 0, 20)
                    cs_data += struct.pack('>II', CSMAGIC_CODEDIRECTORY, 0)  # zero length

                elif strategy == 'bad_magic':
                    cs_data += struct.pack('>III', 0xDEADBEEF, 100, 1)
                    cs_data += os.urandom(80)

                elif strategy == 'huge_hash_size':
                    cs_data += struct.pack('>III', CSMAGIC_EMBEDDED_SIGNATURE, 0, 1)
                    cs_data += struct.pack('>II', 0, 20)
                    cs_data += struct.pack('>II', CSMAGIC_CODEDIRECTORY, 80)
                    cs_data += struct.pack('>I', 0x20400)
                    cs_data += struct.pack('>I', 0)
                    cs_data += struct.pack('>I', 80)
                    cs_data += struct.pack('>I', 52)
                    cs_data += struct.pack('>I', 0)
                    cs_data += struct.pack('>I', 1)
                    cs_data += struct.pack('>I', 4096)
                    cs_data += struct.pack('>B', 255)  # hashSize = 255
                    cs_data += struct.pack('>BBB', 2, 0, 12)
                    cs_data += struct.pack('>I', 0)
                    cs_data += b'test\\x00'

                elif strategy == 'overlapping_blobs':
                    cs_data += struct.pack('>III', CSMAGIC_EMBEDDED_SIGNATURE, 0, 3)
                    # All blobs point to same offset
                    for _ in range(3):
                        cs_data += struct.pack('>II', 0, 32)
                    cs_data += struct.pack('>II', CSMAGIC_CODEDIRECTORY, 40)
                    cs_data += os.urandom(32)
                    struct.pack_into('>I', cs_data, 4, len(cs_data))

                elif strategy == 'truncated_cd':
                    cs_data += struct.pack('>III', CSMAGIC_EMBEDDED_SIGNATURE, 0, 1)
                    cs_data += struct.pack('>II', 0, 20)
                    # CodeDirectory claims 1000 bytes but only 8 present
                    cs_data += struct.pack('>II', CSMAGIC_CODEDIRECTORY, 1000)
                    struct.pack_into('>I', cs_data, 4, len(cs_data))

                # Fix LC_CODE_SIGNATURE size
                struct.pack_into('<I', macho, cs_off - 16 + 12, len(cs_data))

                # Append code signature
                macho += cs_data
                return bytes(macho), strategy


            def fuzz_macho(iterations=1000):
                """Main Mach-O fuzzing loop."""
                os.makedirs(CRASH_DIR, exist_ok=True)
                crashes = 0
                unique = set()

                print(f"FORGE Mach-O Fuzzer — {{iterations}} iterations")
                print(f"Target: spctl --assess / codesign --verify")

                for i in range(iterations):
                    binary, strategy = build_codesig_fuzzed()

                    with tempfile.NamedTemporaryFile(suffix='.bin', delete=False,
                                                      dir='/tmp') as f:
                        f.write(binary)
                        tmppath = f.name

                    try:
                        os.chmod(tmppath, 0o755)
                        result = subprocess.run(
                            ['codesign', '--verify', tmppath],
                            capture_output=True, timeout=5)

                        if result.returncode < 0:
                            crash_hash = hashlib.sha256(binary).hexdigest()[:16]
                            if crash_hash not in unique:
                                unique.add(crash_hash)
                                crashes += 1
                                crash_file = os.path.join(CRASH_DIR,
                                    f'macho_{{strategy}}_{{crash_hash}}.bin')
                                with open(crash_file, 'wb') as f:
                                    f.write(binary)
                                print(f'  [{{i}}] CRASH! strategy={{strategy}}, '
                                      f'sig={{-result.returncode}}')

                    except subprocess.TimeoutExpired:
                        pass
                    finally:
                        os.unlink(tmppath)

                    if (i + 1) % 100 == 0:
                        print(f'  [{{i+1}}] {{crashes}} crashes, {{len(unique)}} unique')

                print(f'Done: {{crashes}} crashes in {{iterations}} iterations')


            if __name__ == "__main__":
                iters = int(sys.argv[1]) if len(sys.argv) > 1 else 1000
                fuzz_macho(iters)
        ''')

    def _gen_format_fuzzer(self, vuln_type: str, info: Dict) -> str:
        """Generate file format fuzzer."""
        return textwrap.dedent(f'''\
            #!/usr/bin/env python3
            """FORGE Format Fuzzer — {info.get('protocol', 'binary')}

            Generates malformed file format inputs.
            Target: {info.get('binary', 'target')}
            CVE: {info.get('cve_id', 'N/A')}

            Generated by FORGE — deterministic, zero AI.
            """
            import os
            import random
            import struct
            import hashlib


            def generate_seeds():
                """Generate seed inputs for format fuzzing."""
                seeds = []

                # Minimal valid-ish header
                seeds.append(struct.pack('<I', 0x89504E47) + os.urandom(64))  # PNG-like
                seeds.append(b'\\xff\\xd8\\xff\\xe0' + os.urandom(64))          # JPEG-like
                seeds.append(b'PK\\x03\\x04' + os.urandom(64))                 # ZIP-like
                seeds.append(b'%PDF-1.4\\n' + os.urandom(64))                  # PDF-like
                seeds.append(b'{{\\n' + os.urandom(64))                          # JSON-like

                # Pathological sizes
                for size_val in [0, 1, 0x7F, 0xFF, 0x7FFF, 0xFFFF, 0x7FFFFFFF, 0xFFFFFFFF]:
                    seeds.append(struct.pack('<I', size_val) + os.urandom(32))
                    seeds.append(struct.pack('>I', size_val) + os.urandom(32))

                return seeds


            def demo():
                """Test format seed generation."""
                seeds = generate_seeds()
                print(f"Generated {{len(seeds)}} seed inputs")
                for i, seed in enumerate(seeds[:5]):
                    print(f"  Seed {{i}}: {{len(seed)}} bytes, "
                          f"sha256={{hashlib.sha256(seed).hexdigest()[:16]}}")
                print("Format fuzzer ready")


            demo()
        ''')

    def _get_mutation_strategies(self, vuln_type: str) -> str:
        """Get mutation strategy code based on vulnerability type."""
        base_strategies = textwrap.dedent('''\
            def bit_flip(data):
                """Flip random bits."""
                if not data:
                    return b'\\x00'
                d = bytearray(data)
                pos = random.randint(0, len(d) - 1)
                d[pos] ^= (1 << random.randint(0, 7))
                return bytes(d)

            def byte_flip(data):
                """Replace random byte."""
                if not data:
                    return b'\\x00'
                d = bytearray(data)
                pos = random.randint(0, len(d) - 1)
                d[pos] = random.randint(0, 255)
                return bytes(d)

            def insert_bytes(data):
                """Insert random bytes."""
                d = bytearray(data)
                pos = random.randint(0, len(d))
                count = random.choice([1, 2, 4, 8, 16, 64, 256, 1024])
                d[pos:pos] = os.urandom(count)
                return bytes(d)

            def delete_bytes(data):
                """Delete random bytes."""
                if len(data) < 2:
                    return data
                d = bytearray(data)
                pos = random.randint(0, len(d) - 1)
                count = random.randint(1, min(16, len(d) - pos))
                del d[pos:pos + count]
                return bytes(d)

            def replace_with_interesting(data):
                """Replace bytes with interesting values."""
                if not data:
                    return b'\\x00'
                d = bytearray(data)
                pos = random.randint(0, max(0, len(d) - 4))
                interesting = random.choice([
                    struct.pack('<I', 0),
                    struct.pack('<I', 0xFFFFFFFF),
                    struct.pack('<I', 0x7FFFFFFF),
                    struct.pack('<I', 0x80000000),
                    struct.pack('<i', -1),
                    b'\\x41' * 4,
                    b'\\x00' * 4,
                    struct.pack('<I', len(data)),
                    struct.pack('<I', len(data) * 2),
                ])
                end = min(pos + len(interesting), len(d))
                d[pos:end] = interesting[:end - pos]
                return bytes(d)

            def duplicate_block(data):
                """Duplicate a block of data."""
                if len(data) < 4:
                    return data * 2
                block_size = random.randint(1, min(256, len(data) // 2))
                pos = random.randint(0, len(data) - block_size)
                block = data[pos:pos + block_size]
                insert_pos = random.randint(0, len(data))
                return data[:insert_pos] + block + data[insert_pos:]

            def crossover(data, other):
                """Crossover two inputs."""
                if not data or not other:
                    return data or other or b'\\x00'
                pos1 = random.randint(0, len(data))
                pos2 = random.randint(0, len(other))
                return data[:pos1] + other[pos2:]
        ''')

        # Add vuln-specific seed generation
        seed_generators = {
            'buffer_overflow': '''\
            def generate_seeds():
                """Seeds targeting buffer overflow."""
                return [
                    b'A' * 256,
                    b'A' * 1024,
                    b'A' * 4096,
                    b'A' * 65536,
                    struct.pack('<I', 0xFFFFFFFF) + b'A' * 256,
                    struct.pack('<I', 0x80000001) + b'\\x00' * 32,
                    b'%n' * 100,
                    b'\\x00' * 256,
                ]
            ''',
            'uaf': '''\
            def generate_seeds():
                """Seeds targeting use-after-free."""
                return [
                    b'\\x00' * 64 + b'\\x41' * 64,
                    struct.pack('<QQ', 0xDEADBEEF, 0xCAFEBABE) * 8,
                    b'alloc\\x00free\\x00use\\x00' * 10,
                    os.urandom(128),
                    b'\\xff' * 64,
                ]
            ''',
            'integer_overflow': '''\
            def generate_seeds():
                """Seeds targeting integer overflow."""
                return [
                    struct.pack('<I', 0x7FFFFFFF),
                    struct.pack('<I', 0x80000000),
                    struct.pack('<I', 0xFFFFFFFF),
                    struct.pack('<II', 0x80000001, 32),
                    struct.pack('<Q', 0xFFFFFFFFFFFFFFFF),
                    struct.pack('<HH', 0xFFFF, 0xFFFF),
                    b'\\xff' * 16,
                ]
            ''',
            'null_deref': '''\
            def generate_seeds():
                """Seeds targeting NULL dereference."""
                return [
                    b'',
                    b'\\x00',
                    b'\\x00' * 64,
                    struct.pack('<Q', 0),
                    struct.pack('<I', 0) + b'A' * 60,
                    b'null\\x00' * 20,
                ]
            ''',
            'format_string': '''\
            def generate_seeds():
                """Seeds targeting format string vulnerabilities."""
                return [
                    b'%s' * 100,
                    b'%n' * 50,
                    b'%x.' * 200,
                    b'AAAA' + b'%08x.' * 100,
                    b'%99999s',
                    b'%p' * 200,
                ]
            ''',
        }

        seed_code = seed_generators.get(vuln_type, seed_generators['buffer_overflow'])
        return base_strategies + '\n' + textwrap.dedent(seed_code)

    def list_harness_types(self) -> List[str]:
        """List available harness types."""
        return list(self.generators.keys())


if __name__ == '__main__':
    gen = FuzzGenerator()

    # Generate a Python mutator for buffer overflow
    target = {
        'binary': '/usr/bin/target',
        'function': 'parse_input',
        'input_type': 'file',
        'cve_id': 'CVE-2024-TEST',
    }
    code = gen.generate('buffer_overflow', target, 'python_mutator')
    print(f"Generated python_mutator: {len(code)} chars, {code.count(chr(10))} lines")

    # Generate Mach-O fuzzer
    code = gen.generate('buffer_overflow', target, 'macho_fuzzer')
    print(f"Generated macho_fuzzer: {len(code)} chars, {code.count(chr(10))} lines")

    # Generate AFL harness
    code = gen.generate('buffer_overflow', target, 'afl_harness')
    print(f"Generated afl_harness: {len(code)} chars, {code.count(chr(10))} lines")

    print("\nAll harness types:", gen.list_harness_types())
