"""Mission Package Builder: Packages complete operation artifacts.

Assembles everything an operator needs into one deployable archive:
  - Exploit/payload code (generated by FORGE)
  - Mutated variants for redundancy
  - Target validation script (pre-check)
  - Cleanup/rollback script
  - OpSec checklist
  - Vulnerability report
  - Kill chain documentation
  - README with deployment instructions

Auto-generates from FORGE outputs: code_assembler, mutation_engine,
kill_chain_engine, report_generator, detection_test.

Part of FORGE Phase P: Professional Output.
"""
# Dependencies: detection_test, mutation_engine, report_generator
# Depended by: none (leaf module)

import hashlib
import json
import os
import shutil
import tarfile
import time
import zipfile
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional


# ─── Package Components ─────────────────────────────────────────────

def _generate_validation_script(target: dict) -> str:
    """Generate target validation script (pre-flight check)."""
    name = target.get('name', 'target')
    platform = target.get('platform', 'linux')

    script = f'''#!/usr/bin/env python3
"""Target Validation Script — Pre-flight check for {name}
Generated by FORGE Mission Package Builder
"""
import os
import sys
import socket
import platform as plat

def validate():
    """Run all pre-flight checks. Returns True if target is valid."""
    checks = []

    # Check 1: Platform
    current_os = plat.system().lower()
    expected = "{platform}"
    if expected in ('windows', 'linux', 'macos', 'darwin'):
        ok = (expected in current_os) or (expected == 'macos' and current_os == 'darwin')
        checks.append(('Platform', ok, f'Expected {{expected}}, got {{current_os}}'))

    # Check 2: Architecture
    arch = plat.machine().lower()
    checks.append(('Architecture', True, arch))
'''

    # Add target-specific checks
    if target.get('path'):
        script += f'''
    # Check 3: Target binary exists
    target_path = "{target['path']}"
    exists = os.path.isfile(target_path)
    checks.append(('Target exists', exists, target_path))
'''

    if target.get('port'):
        script += f'''
    # Check 4: Target port reachable
    port = {target['port']}
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        s.settimeout(3)
        result = s.connect_ex(('127.0.0.1', port))
        s.close()
        reachable = result == 0
        checks.append(('Port reachable', reachable, f'Port {{port}}'))
    except Exception as e:
        checks.append(('Port reachable', False, str(e)))
'''

    if target.get('process'):
        script += f'''
    # Check 5: Target process running
    import subprocess
    proc = "{target['process']}"
    try:
        result = subprocess.run(['pgrep', '-f', proc], capture_output=True)
        running = result.returncode == 0
        checks.append(('Process running', running, proc))
    except Exception:
        checks.append(('Process running', False, 'pgrep not available'))
'''

    script += '''
    # Report
    print("=" * 50)
    print("TARGET VALIDATION REPORT")
    print("=" * 50)
    all_pass = True
    for name, ok, detail in checks:
        status = "PASS" if ok else "FAIL"
        if not ok:
            all_pass = False
        print(f"  [{status}] {name}: {detail}")

    print()
    if all_pass:
        print("  ALL CHECKS PASSED — Target is valid")
    else:
        print("  SOME CHECKS FAILED — Review before proceeding")

    return all_pass

if __name__ == '__main__':
    result = validate()
    sys.exit(0 if result else 1)
'''
    return script


def _generate_cleanup_script(target: dict, artifacts: List[str] = None) -> str:
    """Generate cleanup/rollback script."""
    script = '''#!/usr/bin/env python3
"""Cleanup Script — Remove all operation artifacts
Generated by FORGE Mission Package Builder

WARNING: Run this AFTER operation is complete to remove traces.
"""
import os
import sys
import shutil

ARTIFACTS = [
'''

    if artifacts:
        for a in artifacts:
            script += f"    '{a}',\n"

    script += ''']

def cleanup(dry_run=True):
    """Remove operation artifacts.

    Args:
        dry_run: If True, only show what would be deleted
    """
    print("CLEANUP SCRIPT")
    print("=" * 50)

    removed = 0
    for path in ARTIFACTS:
        path = os.path.expanduser(path)
        if os.path.exists(path):
            if dry_run:
                print(f"  [DRY] Would remove: {path}")
            else:
                if os.path.isdir(path):
                    shutil.rmtree(path)
                else:
                    os.unlink(path)
                print(f"  [DEL] Removed: {path}")
            removed += 1
        else:
            print(f"  [---] Not found: {path}")

    # Clean temp files
    import tempfile
    tmp_dir = os.path.join(tempfile.gettempdir(), 'forge_mission')
    if os.path.isdir(tmp_dir):
        if dry_run:
            print(f"  [DRY] Would remove temp dir: {tmp_dir}")
        else:
            shutil.rmtree(tmp_dir)
            print(f"  [DEL] Removed temp dir: {tmp_dir}")
        removed += 1

    print()
    print(f"  {removed} items {'would be ' if dry_run else ''}removed")
    if dry_run:
        print("  Run with --execute to actually remove files")

if __name__ == '__main__':
    dry = '--execute' not in sys.argv
    cleanup(dry_run=dry)
'''
    return script


def _generate_opsec_checklist(target: dict, techniques: List[str] = None) -> str:
    """Generate OpSec checklist for the operation."""
    checklist = f"""# OpSec Checklist

**Target:** {target.get('name', 'Unknown')}
**Platform:** {target.get('platform', 'Unknown')}
**Generated:** {datetime.now(timezone.utc).isoformat()}

---

## Pre-Operation

- [ ] VPN/proxy chain verified (no IP leaks)
- [ ] Clean VM/container for operation
- [ ] Timestamps set to target timezone
- [ ] DNS leak test passed
- [ ] Logging disabled on operator machine
- [ ] No personally identifiable artifacts in payload

## During Operation

- [ ] Monitor for detection (AV/EDR alerts)
- [ ] Use encrypted C2 channel
- [ ] Minimize dwell time
- [ ] Avoid noisy operations (port scans, mass file access)
- [ ] Limit lateral movement to authorized scope
- [ ] Log all actions for debrief

## Post-Operation

- [ ] Run cleanup script (`python3 cleanup.py --execute`)
- [ ] Verify artifact removal
- [ ] Secure-delete operation logs
- [ ] Update FORGE knowledge base with findings
- [ ] Debrief and document lessons learned
"""

    if techniques:
        checklist += "\n## Techniques Used\n\n"
        for tech in techniques:
            checklist += f"- [ ] {tech} — verify no detection\n"

    checklist += """
## Emergency Procedures

1. If detected: immediately run cleanup script
2. Kill C2 channel
3. Notify team lead
4. Document detection vector for evasion improvement
5. DO NOT attempt to cover tracks under active monitoring

---
*Generated by FORGE Mission Package Builder*
"""
    return checklist


def _generate_readme(mission: dict) -> str:
    """Generate deployment README."""
    name = mission.get('name', 'FORGE Mission Package')
    target = mission.get('target', {})

    readme = f"""# {name}

**Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}
**Target:** {target.get('name', 'Unknown')}
**Platform:** {target.get('platform', 'Unknown')}

---

## Contents

| File | Purpose |
|------|---------|
| `payload/` | Primary payload and variants |
| `validate.py` | Pre-flight target validation |
| `cleanup.py` | Post-operation artifact removal |
| `opsec_checklist.md` | Operational security checklist |
| `report/` | Vulnerability reports (MD + SARIF) |
| `manifest.json` | Package metadata and checksums |

## Quick Start

```bash
# 1. Validate target
python3 validate.py

# 2. Deploy payload
python3 payload/primary.py

# 3. After operation, clean up
python3 cleanup.py --execute
```

## Payload Variants

Multiple functionally equivalent variants are provided for redundancy.
If the primary payload is detected, use an alternate variant.

## Reports

The `report/` directory contains vulnerability documentation in:
- **Markdown** — Human-readable, compatible with Apple Security / BSI
- **SARIF** — Machine-readable, GitHub / Azure DevOps integration
- **JSON** — Structured data for toolchain integration

## Safety

- All payloads are **authorized-use only**
- Run `validate.py` before deployment to confirm target
- Run `cleanup.py --execute` after operation
- Follow `opsec_checklist.md` throughout

---
*Package assembled by FORGE*
"""
    return readme


# ─── Mission Package Builder ────────────────────────────────────────

class MissionPackageBuilder:
    """Assemble complete operation packages from FORGE outputs."""

    def __init__(self, work_dir: str = '/tmp/forge_mission'):
        self.work_dir = work_dir
        self.packages_built = 0

    def build(self, mission: dict) -> dict:
        """Build a complete mission package.

        Args:
            mission: {
                name: str,
                target: {name, platform, path, port, process},
                payload_code: str,         # Primary payload
                variants: List[str],       # Mutated variants
                kill_chain: List[str],     # Kill chain steps
                findings: List[dict],      # Vulnerability findings
                techniques: List[str],     # Evasion techniques used
                artifacts: List[str],      # Files to clean up
            }

        Returns:
            {package_dir, manifest, files_created, archive_path}
        """
        self.packages_built += 1
        timestamp = datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')
        mission_name = mission.get('name', f'mission_{self.packages_built}')
        safe_name = mission_name.replace(' ', '_').lower()

        pkg_dir = os.path.join(self.work_dir, f"{safe_name}_{timestamp}")
        os.makedirs(pkg_dir, exist_ok=True)

        target = mission.get('target', {})
        files_created = []
        manifest = {
            'name': mission_name,
            'created': datetime.now(timezone.utc).isoformat(),
            'target': target,
            'files': {},
            'checksums': {},
        }

        # 1. Payload directory
        payload_dir = os.path.join(pkg_dir, 'payload')
        os.makedirs(payload_dir, exist_ok=True)

        if mission.get('payload_code'):
            primary_path = os.path.join(payload_dir, 'primary.py')
            with open(primary_path, 'w') as f:
                f.write(mission['payload_code'])
            files_created.append('payload/primary.py')
            manifest['checksums']['payload/primary.py'] = hashlib.sha256(
                mission['payload_code'].encode()
            ).hexdigest()

        for i, variant in enumerate(mission.get('variants', []), 1):
            var_code = variant if isinstance(variant, str) else variant.get('variant', variant.get('code', ''))
            var_path = os.path.join(payload_dir, f'variant_{i}.py')
            with open(var_path, 'w') as f:
                f.write(var_code)
            files_created.append(f'payload/variant_{i}.py')
            manifest['checksums'][f'payload/variant_{i}.py'] = hashlib.sha256(
                var_code.encode()
            ).hexdigest()

        # 2. Validation script
        validate_code = _generate_validation_script(target)
        validate_path = os.path.join(pkg_dir, 'validate.py')
        with open(validate_path, 'w') as f:
            f.write(validate_code)
        files_created.append('validate.py')

        # 3. Cleanup script
        cleanup_code = _generate_cleanup_script(target, mission.get('artifacts', []))
        cleanup_path = os.path.join(pkg_dir, 'cleanup.py')
        with open(cleanup_path, 'w') as f:
            f.write(cleanup_code)
        files_created.append('cleanup.py')

        # 4. OpSec checklist
        opsec = _generate_opsec_checklist(target, mission.get('techniques', []))
        opsec_path = os.path.join(pkg_dir, 'opsec_checklist.md')
        with open(opsec_path, 'w') as f:
            f.write(opsec)
        files_created.append('opsec_checklist.md')

        # 5. Reports
        report_dir = os.path.join(pkg_dir, 'report')
        os.makedirs(report_dir, exist_ok=True)

        if mission.get('findings'):
            from o1o_o.core.report_generator import ReportGenerator
            gen = ReportGenerator(analyst='FORGE', organization=mission.get('organization', ''))
            gen.generate_all_reports(mission['findings'])

            for report in gen.reports:
                md_path = os.path.join(report_dir, f'{report.id}.md')
                with open(md_path, 'w') as f:
                    f.write(gen.to_markdown(report))
                files_created.append(f'report/{report.id}.md')

            sarif_path = os.path.join(report_dir, 'forge_results.sarif')
            with open(sarif_path, 'w') as f:
                json.dump(gen.to_sarif(), f, indent=2)
            files_created.append('report/forge_results.sarif')

        # 6. README
        readme = _generate_readme(mission)
        readme_path = os.path.join(pkg_dir, 'README.md')
        with open(readme_path, 'w') as f:
            f.write(readme)
        files_created.append('README.md')

        # 7. Manifest
        manifest['files'] = files_created
        manifest['file_count'] = len(files_created)
        manifest_path = os.path.join(pkg_dir, 'manifest.json')
        with open(manifest_path, 'w') as f:
            json.dump(manifest, f, indent=2)
        files_created.append('manifest.json')

        # 8. Create archive
        archive_path = f"{pkg_dir}.tar.gz"
        with tarfile.open(archive_path, 'w:gz') as tar:
            tar.add(pkg_dir, arcname=os.path.basename(pkg_dir))

        return {
            'package_dir': pkg_dir,
            'archive_path': archive_path,
            'manifest': manifest,
            'files_created': files_created,
            'archive_size': os.path.getsize(archive_path),
        }

    def build_from_forge_output(self, code: str, task_name: str = '',
                                 platform: str = 'linux') -> dict:
        """Build a mission package from FORGE-generated code.

        Convenience method that auto-generates variants and reports.
        """
        # Generate variants
        try:
            from o1o_o.core.mutation_engine import MutationEngine
            me = MutationEngine()
            variants = me.generate_variants(code, count=3, level=3)
        except Exception:
            variants = []

        # Detect and report
        findings = []
        try:
            from o1o_o.core.detection_test import DetectionEngine
            de = DetectionEngine()
            scan = de.scan(code)
            if not scan.clean:
                for det in scan.detections:
                    findings.append({
                        'primitive_type': det['category'],
                        'severity': det['severity'],
                        'target_name': task_name or 'payload',
                        'faulting_function': det['rule'],
                        'platform': platform,
                    })
        except Exception:
            pass

        mission = {
            'name': task_name or 'FORGE Operation',
            'target': {
                'name': task_name or 'target',
                'platform': platform,
            },
            'payload_code': code,
            'variants': [v.get('variant', '') for v in variants],
            'findings': findings,
            'techniques': [],
            'artifacts': [],
        }

        return self.build(mission)

    def format_report(self, result: dict) -> str:
        """Format package build result."""
        lines = [
            f"MISSION PACKAGE BUILT",
            f"{'=' * 50}",
            f"  Directory:  {result['package_dir']}",
            f"  Archive:    {result['archive_path']}",
            f"  Size:       {result['archive_size']:,} bytes",
            f"  Files:      {len(result['files_created'])}",
            f"",
        ]
        for f in result['files_created']:
            lines.append(f"    {f}")

        return '\n'.join(lines)
